### ISSUE TITLE
POE::Loop::Prima on Windows 7 with Strawberry Perl

### ISSUE THREAD

**Issue by vikasnkumar** [dk/POE-Loop-Prima#1]
Hi @dk 
I am having issues installing POE on 64-bit Windows 7 with the latest Strawberry Perl. This seems like an issue with pipes causing hangs in Windows and is an issue with POE for months or years now.

However, my question to you is what other option besides this do I have. I do not want to use POE now since i want to make my GUI application be supported on Windows and Linux/Unix variants. 

I do not invoke any POE::Loop::Prima calls directly, so I am depending on Prima to use POE::Loop::Prima internally. Is this necessary ? Or can I skip POE::Loop::Prima on Windows but use it on Linux and Prima will behave identically ?

Please clarify.

**Comment by vikasnkumar** [comment]
Right now I am optionally loading `POE::Loop::Prima` on Linux and not loading it on Windows.
Here is the code for reference, that you may add to your FAQ

```perl
if ($^O !~ /win32/i) {
    eval { 
         require POE;
         require POE::Kernel;
         POE::Kernel->import({ loop => "Prima" });
         require POE::Session;
    } or die "Unable to load POE::Loop::Prima";
}
```

Sadly, `AnyEvent` also does not install on Windows without forcing tests to pass, so I am just trying to figure out the best way forward. Does `POE::Loop::Prima`, affect anything else in a standard `Prima` GUI application if the application is not using `POE` ?

**Comment by dk** [comment]
I'm not quite sure what is the problem here. Prima does not need POE for anything, but if your app is using POE then you can use POE:L:P as a backend, among others, if f ex you need both POE and native Prima code to work together. This wouldn't work on other backends, naturally.

As for AnyEvent, there is also AnyEvent::Impl::Prima that fills the same niche in the AnyEvent world. Marc Lehmann was especially requesting Prima features back then for this implementation so that module is a first class citizen there.

So, if I'm guessing correct, you need some IO pipelining functionality in your app. Prima is perfectly capable of providing low-level events on its own (see Prima::File and Prima::Timer) but if you need higher-level semantics I would recommend AnyEvent as the best tool out there. A rising star in this domain is Mojo::IO but I haven't looked into making Prima backed for it.

Back then I also made a go with my IO::Lambda which lies in the same category as POE and AnyEvent. You're welcome to take a look at it, if your pipelining logic is more (esp if much more) complex than just callbacks on timer and file events.

/dk

**Comment by vikasnkumar** [comment]
Hi @dk 
There  is no real problem here. I just wanted to ask a few questions around usage of `POE::Loop::Prima`. My codebase for this GUI app is from 2014, and i am reviving it now to work again.
 And the real problem so to speak, is that `POE` installation via CPAN hangs on Windows, and my code had `POE::Loop::Prima` as a dependency. So to get my GUI to be installed from CPAN out of the box, I need all the dependencies to install without _forcing_ the passing of tests.
So I was trying to figure out what `POE::Loop::Prima` is doing in the GUI, and turns out I am not using `POE` in the GUI at all. It was just included, as a way to use it in the future but there is no code that is using `POE`.

Thanks for the pointers towards `Prima::File` and `Prima::Timer`, most likely these will be sufficient for my GUI application.
